# Generated by Django 6.0.3 on 2026-03-30 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('beneficiario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_moneda', models.CharField(max_length=50)),
                ('simbolo', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=150, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.moneda')),
                ('id_beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to='gestion.beneficiario')),
                ('id_usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to='gestion.usuario')),
            ],
            options={
                'indexes': [models.Index(fields=['id_usuario_emisor', 'fecha_transaccion'], name='gestion_tra_id_usua_50e8ac_idx'), models.Index(fields=['id_beneficiario', 'fecha_transaccion'], name='gestion_tra_id_bene_a081f5_idx')],
            },
        ),
    ]
