# Generated by Django 6.0.3 on 2026-03-28 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['id_usuario_emisor', 'fecha_transaccion'], name='gestion_tra_id_usua_50e8ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['id_usuario_receptor', 'fecha_transaccion'], name='gestion_tra_id_usua_672de6_idx'),
        ),
    ]
